### PR TITLE
Respect the end of line character of source files instead of clobbering it to the current platform's default

### PR DESCRIPTION
**Pull request by CAM-Gerlach**
Currently, docstrfmt arbitrarily converts the EoLs of any modified files to the default of whatever platform it happens to be running on, rather than properly respecting the EoL of the original file. Accordingly, this means users on Windows or other non-standard platforms that don't have their git settings set up to prevent this will clobber any file that docstrfmt modifies that they then check into the repo, converting it to non-standard CRLF (that will switch back and forth depending on the last platform to modify it) and modifying every line of the file, leading to a high chance of merge conflicts.

Like the previous issue, I ran into this on my PRAW PR and its a basic but unfortunately not uncommon mistake made by newer/smaller formatting tools that I've fixed for a number of others, so I figured I'd fix it and add some tests for it.

### CODE REVIEW

**Comment by CAM-Gerlach** [comment]
Hey @LilSpazJoekp , could you review and approve the workflow run? Thanks!

**Review by LilSpazJoekp — APPROVED** [review]
Nice catch!

**Comment by CAM-Gerlach** [comment]
@LilSpazJoekp Looks like I missed a couple lines of test coverage; I tweaked the block to use getattr instead, which is both shorter/simpler and avoids the coverage issue.

**Comment by CAM-Gerlach** [comment]
Thanks @LilSpazJoekp !

**Pull request merged**
